files:
  - source: FinalSuspect/*.*
    translation: %original_file_name%
  - source: FinalSuspect/Features/*.*
    translation: Features/%original_file_name%
  - source: FinalSuspect/Guide/*.*
    translation: Guide/%original_file_name%
  - source: FinalSuspect/Options/*.*
    translation: Options/%original_file_name%
